language: cpp
compiler:
    - gcc

os:
    - linux
#    - osx

# use containers
sudo: false 

env:
  - TYPE=Debug DEVSPACE=$HOME

cache:
  directories:
    - $HOME/dcmtk
    - $HOME/openjpeg-version.2.1
  
install:
  #dcmtk
  - cd $HOME
  - "[ -d dcmtk ] || git clone git://git.dcmtk.org/dcmtk.git"
  - cd dcmtk && git pull && mkdir -p build-$TYPE && cd build-$TYPE 
  - cmake .. -DDCMTK_WIDE_CHAR_FILE_IO_FUNCTIONS=1 -DCMAKE_INSTALL_PREFIX=$DEVSPACE/dcmtk/$TYPE
  - make -j8 install
  
  #openjpeg
  - cd $HOME
  - wget https://github.com/uclouvain/openjpeg/archive/version.2.1.tar.gz
  - tar -xzf version.2.1.tar.gz
  - cd openjpeg-version.2.1 && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$DEVSPACE/openjpeg/$TYPE
  - make -j8 install

script:
  - cd $TRAVIS_BUILD_DIR && mkdir -p build-$TYPE && cd build-$TYPE
  - cmake .. -DOPENJPEG=$DEVSPACE/openjpeg/$TYPE -DDCMTK_DIR=$DEVSPACE/dcmtk/$TYPE -DCMAKE_INSTALL_PREFIX=$DEVSPACE/fmjpeg2koj/$TYPE && make -j8 install